// Auto-generated by scripts/generators/playgrounds

export const PresenceStatePlayground = {
  files: {
    "/App.tsx": `import { AnimatePresence, motion, useIsPresent } from "motion/react";
import { useState } from "react";
import styles from "./styles.module.css";

function Card() {
  const isPresent = useIsPresent();

  return (
    <motion.div
      className={styles.card}
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.9 }}
      transition={{
        type: "spring",
        stiffness: 500,
        damping: 30,
      }}
    >
      <span className={styles.status} data-present={isPresent}>
        {isPresent ? "Present" : "Exiting..."}
      </span>
    </motion.div>
  );
}

export default function App() {
  const [isVisible, setIsVisible] = useState(true);

  return (
    <div className={styles.root}>
      <div className={styles.container}>
        <AnimatePresence>{isVisible && <Card key="card" />}</AnimatePresence>
      </div>
      <div className={styles.controls}>
        <button
          type="button"
          className={styles.button}
          onClick={() => setIsVisible(!isVisible)}
        >
          Toggle
        </button>
      </div>
    </div>
  );
}
`,
    "/styles.module.css": `.root {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  height: 100%;
}

.container {
  display: flex;
  flex: 1;
  align-items: center;
  justify-content: center;
  width: 100%;
}

.card {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 160px;
  height: 100px;
  background: var(--gray-1);
  border-radius: 12px;
  box-shadow: var(--shadow-2);
}

.status {
  font-size: 0.875rem;
  font-weight: 500;
}

.status[data-present="true"] {
  color: var(--gray-12);
}

.status[data-present="false"] {
  color: var(--gray-9);
}

.controls {
  display: flex;
  gap: 8px;
  align-items: center;
  justify-content: center;
  width: 100%;
  padding: 16px 0;
  background: var(--gray-1);
  border-top: 1px solid var(--gray-4);
}

.button {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 32px;
  padding: 6px 12px;
  font-size: 14px;
  font-weight: 500;
  color: var(--gray-10);
  cursor: pointer;
  background: var(--gray-1);
  border: none;
  border-radius: 6px;
  box-shadow: var(--shadow-2);
}

.button:hover {
  color: var(--gray-12);
  background: var(--gray-3);
}

.button:active {
  transform: scale(0.98);
}
`,
  },
};
