// Auto-generated by scripts/generators/playgrounds

export const PresenceStatePlayground = {
  files: {
    "/App.tsx": `import { AnimatePresence, motion, useIsPresent } from "motion/react";
import { useState } from "react";
import styles from "./styles.module.css";

const definitions = {
  present: {
    word: "present",
    pronunciation: "/ˈprez.ənt/",
    type: "adjective",
    definition:
      "In a particular place; being in view or at hand. Existing or occurring now, at this time.",
  },
  exiting: {
    word: "exit",
    pronunciation: "/ˈek.sɪt/",
    type: "verb",
    definition:
      "To go out of or leave a place; to depart from a scene, stage, or situation.",
  },
};

function Card() {
  const isPresent = useIsPresent();
  const entry = definitions[isPresent ? "present" : "exiting"];

  return (
    <motion.div
      className={styles.card}
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.9 }}
      transition={{ duration: 0.4, ease: [0.19, 1, 0.22, 1] }}
    >
      <span className={styles.word}>{entry.word}</span>
      <span className={styles.pronunciation}>{entry.pronunciation}</span>
      <span className={styles.type}>{entry.type}</span>
      <p className={styles.definition}>{entry.definition}</p>
    </motion.div>
  );
}

export default function App() {
  const [isVisible, setIsVisible] = useState(true);

  return (
    <div className={styles.root}>
      <div className={styles.container}>
        <AnimatePresence>{isVisible && <Card key="card" />}</AnimatePresence>
      </div>
      <div className={styles.controls}>
        <button
          type="button"
          className={styles.button}
          onClick={() => setIsVisible(!isVisible)}
        >
          Toggle
        </button>
      </div>
    </div>
  );
}
`,
    "/styles.module.css": `.root {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
}

.container {
  display: flex;
  flex: 1;
  align-items: center;
  justify-content: center;
}

.card {
  display: flex;
  flex-direction: column;
  gap: 2px;
  width: 320px;
  padding: 24px;
  background: var(--gray-1);
  border-radius: 12px;
  box-shadow: var(--shadow-2);
}

.word {
  font-size: 20px;
  font-weight: 600;
  line-height: 1.5;
  color: var(--gray-12);
}

.pronunciation {
  font-size: 12px;
  color: var(--gray-10);
}

.type {
  margin-top: 12px;
  font-size: 14px;
  font-style: italic;
  color: var(--gray-10);
}

.definition {
  margin-top: 8px;
  font-family: var(--font-family-serif, Georgia, serif);
  font-size: 16px;
  font-style: italic;
  line-height: 1.5;
  color: var(--gray-12);
}

.controls {
  display: flex;
  gap: 8px;
  align-items: center;
  justify-content: center;
  width: 100%;
  padding: 16px 0;
  background: var(--gray-2);
  border-top: 1px solid var(--gray-4);
}

.button {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 32px;
  padding: 6px 12px;
  font-size: 14px;
  font-weight: 500;
  color: var(--gray-10);
  cursor: pointer;
  background: var(--gray-1);
  border: none;
  border-radius: 6px;
  box-shadow: var(--shadow-2);
}

.button:hover {
  color: var(--gray-12);
  background: var(--gray-3);
}

.button:active {
  transform: scale(0.98);
}
`,
  },
};
