// Auto-generated by scripts/generators/playgrounds

export const AnimatedHeightPlayground = {
  files: {
    "/App.tsx": `import { AnimatePresence, MotionConfig, motion } from "motion/react";
import { useCallback, useEffect, useState } from "react";
import styles from "./styles.module.css";

function useMeasure<T extends HTMLElement = HTMLElement>(): [
  (node: T | null) => void,
  { width: number; height: number },
] {
  const [element, setElement] = useState<T | null>(null);
  const [bounds, setBounds] = useState({ width: 0, height: 0 });

  const ref = useCallback((node: T | null) => {
    setElement(node);
  }, []);

  useEffect(() => {
    if (!element) return;

    const observer = new ResizeObserver(([entry]) => {
      setBounds({
        width: entry.contentRect.width,
        height: entry.contentRect.height,
      });
    });

    observer.observe(element);
    return () => observer.disconnect();
  }, [element]);

  return [ref, bounds];
}

export default function App() {
  const [expanded, setExpanded] = useState(false);
  const [ref, bounds] = useMeasure();

  return (
    <div className={styles.container}>
      <MotionConfig
        transition={{
          duration: 0.4,
          ease: [0.19, 1, 0.22, 1],
          delay: 0.05,
        }}
      >
        <div className={styles.card}>
          <motion.div
            animate={{
              height: bounds.height > 0 ? bounds.height : "auto",
            }}
            className={styles.content}
          >
            <div ref={ref} className={styles.inner}>
              <p className={styles.text}>
                Containers on the web snap to their new size instantly when
                content changes. By measuring the bounds of a container and
                animating to those values, we can make these transitions feel
                smooth and intentional.
              </p>
              <AnimatePresence mode="popLayout">
                {expanded && (
                  <motion.p
                    initial={{ opacity: 0, filter: "blur(8px)" }}
                    animate={{ opacity: 1, filter: "blur(0px)" }}
                    exit={{ opacity: 0, filter: "blur(8px)" }}
                    className={styles.text}
                  >
                    This technique uses a ref to track the height of the inner
                    content. When the content changes, the measured height
                    updates and Motion animates the outer container to match.
                    The inner div always has its natural height, so the content
                    is never clipped or distorted.
                  </motion.p>
                )}
              </AnimatePresence>
            </div>
          </motion.div>
          <button
            type="button"
            className={styles.button}
            onClick={() => setExpanded((prev) => !prev)}
          >
            {expanded ? "Show Less" : "Read More"}
          </button>
        </div>
      </MotionConfig>
    </div>
  );
}
`,
    "/styles.module.css": `.container {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 32px 16px;
}

.card {
  display: flex;
  flex-direction: column;
  gap: 12px;
  width: 100%;
  max-width: 400px;
  padding: 20px;
  background: var(--gray-1);
  border-radius: 12px;
  box-shadow: var(--shadow-2);
}

.content {
  overflow: hidden;
}

.inner {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.text {
  margin: 0;
  font-size: 14px;
  line-height: 1.6;
  color: var(--gray-11);
  letter-spacing: var(--font-letter-spacing-14px);
}

.button {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 32px;
  padding: 6px 12px;
  font-size: 14px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-10);
  cursor: pointer;
  outline: none;
  background: var(--gray-3);
  border: none;
  border-radius: 8px;
}

.button:hover {
  color: var(--gray-12);
  background: var(--gray-4);
}

.button:active {
  transform: scale(0.98);
}
`,
  },
};
