// Auto-generated by scripts/generate-playgrounds.ts

export const SpringDemoPlayground = {
  files: {
    "/App.tsx": `import { animate, motion, useMotionValue, useVelocity } from "motion/react";
import { useRef, useState } from "react";
import { Button } from "@/components/button";
import { Controls } from "@/components/controls";
import styles from "./styles.module.css";

const easeOutQuint = [0.23, 1, 0.32, 1] as const;

export default function App() {
  const containerRef = useRef<HTMLDivElement>(null);
  const x = useMotionValue(0);
  const y = useMotionValue(0);
  const xVelocity = useVelocity(x);
  const [useSpring, setUseSpring] = useState(true);

  const handleDragEnd = () => {
    if (!containerRef.current) return;

    const currentX = x.get();
    const currentY = y.get();
    const velocity = xVelocity.get();

    // Calculate positions of the two endpoints relative to center
    const leftX = -140;
    const rightX = 140;
    const endpointY = 0;

    // Factor in velocity - if flicking fast, go in that direction
    let targetX: number;
    if (Math.abs(velocity) > 500) {
      targetX = velocity > 0 ? rightX : leftX;
    } else {
      // Calculate distance to each endpoint
      const distToLeft = Math.sqrt(
        (currentX - leftX) ** 2 + (currentY - endpointY) ** 2,
      );
      const distToRight = Math.sqrt(
        (currentX - rightX) ** 2 + (currentY - endpointY) ** 2,
      );
      targetX = distToLeft < distToRight ? leftX : rightX;
    }

    const transition = useSpring
      ? { type: "spring" as const, stiffness: 300, damping: 20, velocity }
      : { duration: 0.4, ease: easeOutQuint };

    animate(x, targetX, transition);
    animate(y, 0, transition);
  };

  return (
    <div className={styles.root}>
      <div className={styles.container} ref={containerRef}>
        <div className={styles.track}>
          <div className={styles.endpoint} data-position="left" />
          <div className={styles.endpoint} data-position="right" />
        </div>
        <motion.div
          className={styles.ball}
          style={{ x, y }}
          drag
          dragElastic={0.5}
          dragMomentum={false}
          onDragEnd={handleDragEnd}
          whileDrag={{ scale: 1.1, cursor: "grabbing" }}
        />
      </div>
      <Controls className={styles.controls}>
        <Button onClick={() => setUseSpring(!useSpring)}>
          {useSpring ? "Spring" : "Ease"}
        </Button>
      </Controls>
    </div>
  );
}
`,
    "/styles.module.css": `.root {
  display: flex;
  flex: 1;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 384px;
}

.container {
  position: relative;
  display: flex;
  flex: 1;
  flex-direction: column;
  gap: 24px;
  align-items: center;
  justify-content: center;
  width: 100%;
}

.track {
  position: absolute;
  display: flex;
  gap: 280px;
  align-items: center;
  justify-content: center;
  pointer-events: none;
}

.endpoint {
  width: 12px;
  height: 12px;
  background: var(--gray-6);
  border-radius: 50%;
}

.ball {
  position: relative;
  width: 80px;
  height: 80px;
  touch-action: none;
  cursor: grab;
  background: var(--gray-1);
  border-radius: 50%;
  box-shadow: var(--shadow-2);
}

.ball:active {
  cursor: grabbing;
}

.controls {
  z-index: 10;
}
`,
  },
};
