// Auto-generated by scripts/generate-playgrounds.ts

export const ActionFeedbackDemoPlayground = {
  files: {
    "/App.tsx": `import { Toast } from "@base-ui/react/toast";
import { Button } from "@/components/button";
import { Controls } from "@/components/controls";
import { sounds } from "@/lib/sounds";
import styles from "./styles.module.css";

type ActionType = "success" | "error" | "warning";

export default function App() {
  const { toasts, add } = Toast.useToastManager();

  const handleAction = (type: ActionType) => {
    sounds[type]();

    const messages: Record<ActionType, string> = {
      success: "Payment processed successfully",
      error: "Card declined. Please try again.",
      warning: "Your session will expire soon",
    };

    add({
      type,
      description: messages[type],
    });
  };

  return (
    <div className={styles.container}>
      <div className={styles.area}>
        <Toast.Viewport className={styles.viewport}>
          {toasts.map((toast) => (
            <Toast.Root
              key={toast.id}
              toast={toast}
              className={styles.toast}
              data-type={toast.type}
            >
              <Toast.Content className={styles.content} data-type={toast.type}>
                <Toast.Description className={styles.message} />
              </Toast.Content>
            </Toast.Root>
          ))}
        </Toast.Viewport>
      </div>
      <Controls className={styles.actions}>
        <Button onClick={() => handleAction("success")}>Success</Button>
        <Button onClick={() => handleAction("error")}>Error</Button>
        <Button onClick={() => handleAction("warning")}>Warning</Button>
      </Controls>
    </div>
  );
}
`,
    "/styles.module.css": `.container {
  display: flex;
  flex-direction: column;
  align-items: flex-end;
  justify-content: flex-end;
  width: 100%;
}

.actions {
  display: flex;
  gap: 12px;
  justify-content: center;
  padding: 12px;

  [data-button] {
    width: 100%;
    border-radius: 8px;
  }
}

.area {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 256px;
}

.viewport {
  position: relative;
  width: 280px;
  height: 48px;
  outline: 0;
}

.toast {
  position: absolute;
  top: 0;
  right: 0;
  left: 0;
  z-index: calc(1000 - var(--toast-index));
  box-sizing: border-box;
  width: 256px;
  margin: 0 auto;
  pointer-events: auto;
  cursor: default;
  user-select: none;
  background: var(--gray-1);
  border-radius: 12px;
  box-shadow: var(--shadow-2);
  opacity: calc(1 - var(--toast-index) * 0.25);
  transform: translateY(calc(var(--toast-index) * 16px))
    scale(calc(1 - var(--toast-index) * 0.05));
  transform-origin: center center;
  transition:
    transform 0.4s cubic-bezier(0.22, 1, 0.36, 1),
    opacity 0.4s;
}

.toast[data-starting-style] {
  opacity: 0;
  transform: translateY(-16px) scale(0.9);
}

.toast[data-ending-style] {
  opacity: 0;
  transform: translateY(16px) scale(0.9);
}

.toast[data-limited] {
  opacity: 0;
}

.content {
  display: flex;
  gap: 10px;
  align-items: center;
  justify-content: center;
  padding: 8px 16px;
  white-space: nowrap;
  transition: opacity 0.25s;
}

.content[data-behind] {
  opacity: 0;
}

.message {
  font-size: 14px;
  font-weight: var(--font-weight-normal);
  letter-spacing: var(--font-letter-spacing-14px);
}
`,
  },
};
