// Auto-generated by scripts/generators/playgrounds

export const ModesDemoPlayground = {
  files: {
    "/App.tsx": `import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";
import styles from "./styles.module.css";

type Mode = "sync" | "wait" | "popLayout";

const modes: Mode[] = ["sync", "wait", "popLayout"];

function ModeExample({ mode, show }: { mode: Mode; show: boolean }) {
  return (
    <div className={styles.example}>
      <div className={styles.label}>{mode}</div>
      <div className={styles.icon}>
        <AnimatePresence mode={mode}>
          <motion.div
            key={show ? "a" : "b"}
            initial={{ opacity: 0, scale: 0.8, filter: "blur(2px)" }}
            animate={{ opacity: 1, scale: 1, filter: "blur(0px)" }}
            exit={{ opacity: 0, scale: 0.8, filter: "blur(2px)" }}
            transition={{ duration: 0.4, ease: [0.19, 1, 0.22, 1] }}
          >
            {show ? "A" : "B"}
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
}

export default function App() {
  const [show, setShow] = useState(true);

  return (
    <div className={styles.root}>
      <div className={styles.grid}>
        {modes.map((mode) => (
          <ModeExample key={mode} mode={mode} show={show} />
        ))}
      </div>
      <div className={styles.controls}>
        <button
          type="button"
          className={styles.button}
          onClick={() => setShow((prev) => !prev)}
        >
          Toggle
        </button>
      </div>
    </div>
  );
}
`,
    "/styles.module.css": `.root {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  height: 100%;
}

.grid {
  display: grid;
  flex: 1;
  grid-template-columns: repeat(3, 1fr);
  gap: 2rem;
  align-content: center;
  width: 100%;
  padding-inline: 24px;
}

.example {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  align-items: center;
}

.label {
  font-family: var(--font-mono);
  font-size: 0.875rem;
  font-weight: 500;
  color: var(--gray-11);
}

.icon {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 48px;
  height: 48px;
  font-size: 16px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-12);
  background: var(--gray-1);
  border-radius: 100px;
  box-shadow: var(--shadow-2);
}

.controls {
  display: flex;
  gap: 8px;
  align-items: center;
  justify-content: center;
  width: 100%;
  padding: 16px 0;
  background: var(--gray-2);
  border-top: 1px solid var(--gray-4);
}

.button {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 32px;
  padding: 6px 12px;
  font-size: 14px;
  font-weight: 500;
  color: var(--gray-10);
  cursor: pointer;
  background: var(--gray-1);
  border: none;
  border-radius: 6px;
  box-shadow: var(--shadow-2);
}

.button:hover {
  color: var(--gray-12);
  background: var(--gray-3);
}

.button:active {
  transform: scale(0.98);
}
`,
  },
};
