// Auto-generated by scripts/generate-playgrounds.ts

export const BeforeAndAfterDemoPlayground = {
  files: {
    "/App.tsx": `import { Button } from "@/components/button";
import styles from "./styles.module.css";

export default function App() {
  return (
    <div className={styles.container}>
      <Button variant="ghost">::before</Button>
    </div>
  );
}
`,
    "/styles.module.css": `.container {
  padding: 48px 24px;
}
`,
  },
};
