// Auto-generated by scripts/generators/playgrounds

export const NestedExitsPlayground = {
  files: {
    "/App.tsx": `import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";
import { Button } from "@/components/button";
import { Controls } from "@/components/controls";
import styles from "./styles.module.css";

function ChildItem({ label }: { label: string }) {
  return (
    <motion.div
      className={styles.child}
      initial={{ opacity: 0, scale: 0.8 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.8 }}
      transition={{
        type: "spring",
        stiffness: 500,
        damping: 30,
      }}
    >
      {label}
    </motion.div>
  );
}

export default function App() {
  const [showParent, setShowParent] = useState(true);
  const [propagate, setPropagate] = useState(true);

  return (
    <div className={styles.root}>
      <div className={styles.container}>
        <AnimatePresence>
          {showParent && (
            <motion.div
              key="parent"
              className={styles.parent}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              transition={{
                type: "spring",
                stiffness: 400,
                damping: 30,
              }}
            >
              <span className={styles.label}>Parent</span>
              <div className={styles.children}>
                <AnimatePresence propagate={propagate}>
                  <ChildItem key="a" label="A" />
                  <ChildItem key="b" label="B" />
                  <ChildItem key="c" label="C" />
                </AnimatePresence>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
      <Controls>
        <Button onClick={() => setShowParent(!showParent)}>
          {showParent ? "Remove Parent" : "Show Parent"}
        </Button>
        <Button onClick={() => setPropagate(!propagate)}>
          propagate: {propagate ? "true" : "false"}
        </Button>
      </Controls>
    </div>
  );
}
`,
    "/styles.module.css": `.root {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
  align-items: center;
  width: 100%;
}

.container {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 200px;
}

.parent {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px;
  background: var(--gray-3);
  border: 1px solid var(--gray-6);
  border-radius: 12px;
}

.label {
  font-size: 12px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-10);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.children {
  display: flex;
  gap: 8px;
}

.child {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 48px;
  height: 48px;
  font-size: 14px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-12);
  background: var(--gray-5);
  border-radius: 8px;
}
`,
  },
};
