// Auto-generated by scripts/generators/playgrounds

export const StagingPlayground = {
  files: {
    "/App.tsx": `import { Dialog } from "@base-ui/react/dialog";
import type { Variants } from "motion/react";
import { AnimatePresence, MotionConfig, motion } from "motion/react";
import { useEffect, useRef, useState } from "react";
import {
  Bell2Icon,
  DotGrid1X3HorizontalIcon,
  SquareBehindSquare2Icon,
} from "@/icons";
import styles from "./styles.module.css";

interface Wallet {
  id: string;
  name: string;
  balance: number;
  address: string;
  color: string;
}

const COLORS = [
  "#ee4562",
  "#ec4899",
  "#d946ef",
  "#9553f9",
  "#5647f0",
  "#0680fa",
  "#4dafff",
  "#0ea5e9",
  "#14bbc7",
  "#10b981",
  "#34c759",
  "#84cc16",
  "#eab308",
  "#f59e0b",
  "#f97316",
  "#ef4444",
  "#cdb35e",
  "#c48c54",
  "#023364",
  "#1a1a1a",
] as const;

const LAYOUT_ID = {
  wallet: "wallet",
  topTrailing: "top-trailing",
  bottomTrailing: "bottom-trailing",
  topLeading: "top-leading",
  bottomLeading: "bottom-leading",
} as const;

const VARIANTS = {
  blur: {
    hidden: { filter: "blur(10px)" },
    visible: { filter: "blur(0px)" },
  },
  picker: {
    hidden: {
      opacity: 0,
      translateY: 32,
      filter: "blur(12px)",
      scale: 0.9,
    },
    visible: {
      opacity: 1,
      filter: "blur(0px)",
      translateY: 0,
      scale: 1,
    },
    exit: {
      opacity: 0,
      translateY: 32,
      scale: 0,
      filter: "blur(12px)",
      transition: { duration: 0.2 },
    },
  },
} as const satisfies Record<string, Variants>;

export default function App() {
  const inputRef = useRef<HTMLInputElement>(null);

  const [wallet, setWallet] = useState<Wallet>({
    id: "1",
    name: "Raphael",
    balance: 57_206,
    address: "0x1234567890abcdef1234567890abcdef12345678",
    color: COLORS[10],
  });

  const [isOpen, setIsOpen] = useState(false);
  const [isEditingName, setIsEditingName] = useState(false);
  const [isPickingColor, setIsPickingColor] = useState(false);

  const bg = wallet.color;

  const label = !isOpen
    ? ""
    : isEditingName
      ? "Done"
      : isPickingColor
        ? "Edit Nickname"
        : "Customize";

  function copyAddress() {
    navigator.clipboard.writeText(wallet.address);
  }

  function handleNameChange(name: string) {
    setWallet((w) => ({ ...w, name }));
  }

  function finishNameEdit() {
    setIsEditingName(false);
    setIsPickingColor(false);

    if (!wallet.name.trim()) {
      setWallet((w) => ({ ...w, name: "New Wallet" }));
    }
  }

  function handleCustomizeClick() {
    if (isEditingName) {
      finishNameEdit();
      return;
    }

    if (isPickingColor) {
      setIsPickingColor(false);
      setIsEditingName(true);
      return;
    }

    setIsPickingColor(true);
  }

  function handleSaveColors() {
    setIsPickingColor(false);
  }

  function handleDialogChange(open: boolean) {
    if (open) {
      setIsOpen(true);
    } else {
      setIsEditingName(false);
      setIsPickingColor(false);
      setTimeout(() => setIsOpen(false), 200);
    }
  }

  useEffect(() => {
    if (isEditingName && inputRef.current) {
      const el = inputRef.current;
      const len = el.value.length;
      el.focus();
      el.setSelectionRange(len, len);
    }
  }, [isEditingName]);

  return (
    <div className={styles.root}>
      <MotionConfig transition={{ type: "spring", bounce: 0, duration: 0.5 }}>
        <Dialog.Root open={isOpen} onOpenChange={handleDialogChange}>
          <AnimatePresence initial={false} mode="popLayout">
            {!isOpen && (
              <Dialog.Trigger
                nativeButton={false}
                style={{ cursor: "pointer" }}
                render={
                  <motion.div
                    className={styles.wallet}
                    layoutId={LAYOUT_ID.wallet}
                    style={{ background: bg, width: 200 }}
                    whileHover={{ scale: 0.98, opacity: 0.8 }}
                    whileTap={{ scale: 0.95 }}
                  >
                    <div className={styles.column}>
                      <motion.div
                        layoutId={LAYOUT_ID.topTrailing}
                        className={styles.icon}
                      >
                        <Bell2Icon
                          className={styles.shape}
                          color="var(--white-a12)"
                        />
                      </motion.div>

                      <motion.span
                        layoutId={LAYOUT_ID.bottomTrailing}
                        className={styles.details}
                      >
                        <input
                          data-text="primary"
                          className={styles.text}
                          type="text"
                          value={wallet.name}
                          disabled
                          placeholder="Wallet Name"
                          aria-label="Wallet name"
                        />
                        <motion.p data-text="secondary" className={styles.text}>
                          \${wallet.balance.toLocaleString()}
                        </motion.p>
                      </motion.span>
                    </div>

                    <div className={styles.column}>
                      <motion.div
                        role="button"
                        tabIndex={0}
                        aria-label="Wallet options"
                        variants={VARIANTS.blur}
                        initial="hidden"
                        animate="visible"
                        exit="hidden"
                        whileHover={{ scale: 0.98 }}
                        whileTap={{ scale: 0.95 }}
                        className={styles.options}
                        layoutId={LAYOUT_ID.topLeading}
                      >
                        <DotGrid1X3HorizontalIcon color="var(--white-a12)" />
                      </motion.div>

                      <motion.div
                        layout
                        layoutId={LAYOUT_ID.bottomLeading}
                        initial={{ opacity: 0 }}
                        animate={{ opacity: 0, filter: "blur(10px)" }}
                        exit={{ opacity: 0 }}
                        style={{
                          display: "flex",
                          alignItems: "center",
                          justifyContent: "center",
                          width: "fit-content",
                          height: 32,
                          padding: "0 16px",
                          color: "var(--white-a10)",
                          background: "var(--white-a4)",
                          borderRadius: 100,
                        }}
                      >
                        <motion.p
                          className={styles.text}
                          variants={VARIANTS.blur}
                          initial="hidden"
                          animate="visible"
                          exit="hidden"
                        >
                          Customize
                        </motion.p>
                      </motion.div>
                    </div>
                  </motion.div>
                }
              />
            )}
          </AnimatePresence>

          <Dialog.Portal keepMounted>
            <Dialog.Backdrop className={styles.backdrop} />
            <Dialog.Title className={styles.sronly}>
              Wallet Settings
            </Dialog.Title>

            <AnimatePresence initial={false} mode="wait">
              {isOpen && (
                <Dialog.Popup
                  render={
                    <div className={styles.popup}>
                      <AnimatePresence mode="popLayout">
                        {isPickingColor && (
                          <motion.div
                            className={styles.picker}
                            key="picker"
                            variants={VARIANTS.picker}
                            initial="hidden"
                            animate="visible"
                            exit="exit"
                          >
                            <fieldset
                              className={styles.swatch}
                              aria-label="Color options"
                            >
                              {COLORS.map((c) => (
                                <motion.div
                                  key={c}
                                  role="button"
                                  tabIndex={0}
                                  aria-label={\`Select color \${c}\`}
                                  aria-pressed={wallet.color === c}
                                  className={styles.color}
                                  style={{ background: c }}
                                  onClick={() =>
                                    setWallet((w) => ({ ...w, color: c }))
                                  }
                                  onKeyDown={(e) =>
                                    (e.key === "Enter" || e.key === " ") &&
                                    setWallet((w) => ({ ...w, color: c }))
                                  }
                                  whileHover={{ opacity: 0.8 }}
                                  data-selected={wallet.color === c}
                                />
                              ))}
                            </fieldset>
                            <motion.div
                              role="button"
                              tabIndex={0}
                              aria-label="Save color selection"
                              onClick={handleSaveColors}
                              onKeyDown={(e) =>
                                (e.key === "Enter" || e.key === " ") &&
                                handleSaveColors()
                              }
                              whileHover={{ scale: 0.98, opacity: 0.8 }}
                              whileTap={{ scale: 0.95 }}
                              style={{ background: bg }}
                              className={styles.save}
                            >
                              Save
                            </motion.div>
                          </motion.div>
                        )}
                      </AnimatePresence>

                      <motion.div
                        className={styles.wallet}
                        layoutId={LAYOUT_ID.wallet}
                        style={{ background: bg, width: 400 }}
                      >
                        <div className={styles.column}>
                          <motion.div
                            layoutId={LAYOUT_ID.topTrailing}
                            className={styles.icon}
                          >
                            <Bell2Icon
                              className={styles.shape}
                              color="var(--white-a12)"
                            />
                          </motion.div>

                          <motion.span
                            layoutId={LAYOUT_ID.bottomTrailing}
                            className={styles.details}
                          >
                            <input
                              ref={inputRef}
                              data-text="primary"
                              className={styles.text}
                              type="text"
                              value={wallet.name}
                              disabled={!isEditingName}
                              placeholder="Wallet Name"
                              aria-label="Wallet name"
                              onChange={(e) => handleNameChange(e.target.value)}
                              onBlur={finishNameEdit}
                              onKeyDown={(e) =>
                                e.key === "Enter" && finishNameEdit()
                              }
                            />
                            <motion.p
                              data-text="secondary"
                              className={styles.text}
                              animate={{ opacity: isEditingName ? 0.5 : 1 }}
                            >
                              \${wallet.balance.toLocaleString()}
                            </motion.p>
                          </motion.span>
                        </div>

                        <div className={styles.column}>
                          <motion.div
                            role="button"
                            tabIndex={0}
                            aria-label="Copy wallet address to clipboard"
                            variants={VARIANTS.blur}
                            initial="hidden"
                            animate={{
                              ...VARIANTS.blur.visible,
                              opacity: isEditingName ? 0.5 : 1,
                            }}
                            exit="hidden"
                            whileHover={{ scale: 0.98 }}
                            whileTap={{ scale: 0.95 }}
                            layoutId={LAYOUT_ID.topLeading}
                            className={styles.copy}
                            onClick={copyAddress}
                            onKeyDown={(e) =>
                              (e.key === "Enter" || e.key === " ") &&
                              copyAddress()
                            }
                          >
                            <p data-text="primary" className={styles.text}>
                              Copy Address
                            </p>
                            <SquareBehindSquare2Icon
                              strokeWidth={3}
                              className={styles.symbol}
                            />
                          </motion.div>

                          <motion.div
                            role="button"
                            tabIndex={0}
                            aria-label={label}
                            layout
                            layoutId={LAYOUT_ID.bottomLeading}
                            className={styles.customize}
                            initial={{ opacity: 0 }}
                            animate={{ opacity: 1, filter: "blur(0px)" }}
                            exit={{ opacity: 0 }}
                            whileHover={{ scale: 0.98, opacity: 0.8 }}
                            whileTap={{ scale: 0.95 }}
                            style={{
                              color: isEditingName ? bg : "var(--white-a10)",
                              background: isEditingName
                                ? "var(--white-a12)"
                                : "var(--white-a4)",
                              borderRadius: 100,
                            }}
                            onClick={handleCustomizeClick}
                            onKeyDown={(e) =>
                              (e.key === "Enter" || e.key === " ") &&
                              handleCustomizeClick()
                            }
                          >
                            <motion.p
                              key={label}
                              className={styles.text}
                              variants={VARIANTS.blur}
                              initial="hidden"
                              animate="visible"
                              exit="hidden"
                            >
                              {label}
                            </motion.p>
                          </motion.div>
                        </div>
                      </motion.div>
                    </div>
                  }
                />
              )}
            </AnimatePresence>
          </Dialog.Portal>
        </Dialog.Root>
      </MotionConfig>
    </div>
  );
}
`,
    "/styles.module.css": `.root {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 384px;
}

.backdrop {
  position: fixed;
  inset: 0;
  z-index: 2147483647;
  background-color: var(--gray-1);
  opacity: 0.9;
  transition: all 0.2s ease;
}

.backdrop[data-starting-style],
.backdrop[data-ending-style] {
  opacity: 0;
}

.popup {
  position: fixed;
  inset: 0;
  z-index: 2147483647;
  display: flex;
  flex-direction: column-reverse;
  gap: 24px;
  align-items: center;
  justify-content: center;
  margin: auto;
  pointer-events: none;
}

.popup > * {
  pointer-events: auto;
}

.sronly {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  white-space: nowrap;
  border: 0;
  clip: rect(0, 0, 0, 0);
}

.wallet {
  --offset: 16px;

  position: relative;
  display: flex;
  justify-content: space-between;
  aspect-ratio: 3 / 1.8;
  padding: var(--offset);
  border-radius: 20px;
  transition: background 0.2s ease;
}

.wallet:focus {
  outline: none;
  box-shadow: none;
}

.column {
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  height: 100%;
}

.column:nth-child(2) {
  align-items: flex-end;
}

.icon {
  display: flex;
  width: 30px;
  height: 30px;
}

.shape {
  fill: var(--white-a12);
}

.details {
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.text {
  display: flex;
  margin: 0;
  font-size: 16px;
  letter-spacing: var(--font-letter-spacing-16px);
  font-weight: var(--font-weight-semibold);
  line-height: normal;
  white-space: nowrap;
  field-sizing: content;
  color: unset;
  will-change: filter;
}

.text[data-text="primary"] {
  color: var(--white-a12);
}

.text[data-text="secondary"] {
  color: var(--white-a8);
}

.text::selection {
  background: var(--white-a4);
}

.text:focus {
  outline: none;
}

.text::placeholder {
  color: var(--white-a6);
}

.options {
  display: flex;
  flex-direction: column;
  width: 24px;
  height: 24px;
  padding: 4px;
  color: var(--white-a10);
  cursor: pointer;
  background: var(--white-a4);
  border-radius: 100%;
}

.options:focus {
  outline: none;
  box-shadow: none;
}

.copy {
  display: flex;
  gap: 8px;
  align-items: center;
  justify-content: center;
  cursor: pointer;
}

.copy:focus {
  outline: none;
  box-shadow: none;
}

.symbol {
  width: 16px;
  height: 16px;
  color: var(--white-a8);
}

.customize {
  display: flex;
  align-items: center;
  justify-content: center;
  width: fit-content;
  height: 32px;
  padding: 0 16px;
  color: unset;
  cursor: pointer;
  background: var(--white-a4);
  border-radius: 16px;
}

.picker {
  display: flex;
  flex-direction: column;
  gap: 16px;
  justify-content: flex-end;
  padding: 16px;
  background: transparent;
  border-radius: 16px;
}

.swatch {
  display: grid;
  grid-template-columns: repeat(5, 1fr);
  gap: 8px;
  width: 100%;
}

.color {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 32px;
  aspect-ratio: 1;
  cursor: pointer;
  border-radius: 100%;
  transition: all 0.2s ease;
}

.color::before {
  position: absolute;
  inset: 4px;
  content: "";
  border-radius: 100px;
  box-shadow: inset 0 0 0 3px var(--white-a12);
  opacity: 0;
  transform: scale(0);
  transition: all 0.2s ease;
}

.color[data-selected="true"]::before {
  opacity: 1;
  transform: scale(1);
}

.save {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 40px;
  padding: 0 16px;
  font-size: 14px;
  font-weight: var(--font-weight-semibold);
  letter-spacing: var(--font-letter-spacing-14px);
  line-height: normal;
  white-space: nowrap;
  field-sizing: content;
  color: var(--white-a12);
  cursor: pointer;
  border-radius: 16px;
  will-change: filter;
}
`,
  },
};
