// Auto-generated by scripts/generators/playgrounds

export const EaseVsSpringPlayground = {
  files: {
    "/App.tsx": `import { motion, type Transition } from "motion/react";
import { useState } from "react";
import { Button } from "@/components/button";
import { Controls } from "@/components/controls";
import styles from "./styles.module.css";

type Animation = {
  label: string;
  transition: Transition;
};

const ease: Animation = {
  label: "Easing",
  transition: {
    duration: 0.5,
    ease: [0.19, 1, 0.22, 1],
  },
};

const spring: Animation = {
  label: "Spring",
  transition: {
    type: "spring",
    stiffness: 300,
    damping: 15,
    mass: 1,
  },
};

const animations = [ease, spring];

type BoxProps = {
  label: string;
  isExpanded: boolean;
  transition: Transition;
};

function Box({ label, isExpanded, transition }: BoxProps) {
  return (
    <div className={styles.box}>
      <div className={styles.scale}>
        <div className={styles.marker} />
        <motion.div
          className={styles.ball}
          animate={{
            width: isExpanded ? 128 : 32,
            height: isExpanded ? 128 : 32,
          }}
          transition={transition}
        />
      </div>
      <span className={styles.label}>{label}</span>
    </div>
  );
}

export default function App() {
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div className={styles.container}>
      <div className={styles.visualization}>
        {animations.map(({ label, transition }) => (
          <Box
            key={label}
            label={label}
            isExpanded={isExpanded}
            transition={transition}
          />
        ))}
      </div>

      <Controls>
        <Button onClick={() => setIsExpanded((prev) => !prev)}>Animate</Button>
      </Controls>
    </div>
  );
}
`,
    "/styles.module.css": `.container {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 384px;
}

.visualization {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
}

.label {
  font-size: 14px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-11);
  text-align: center;
  letter-spacing: var(--font-letter-spacing-14px);
}

.box {
  position: relative;
  display: flex;
  flex-direction: column;
  gap: 24px;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  padding: 24px;
}

.marker {
  position: absolute;
  top: 50%;
  left: 50%;
  z-index: 1;
  width: 150px;
  height: 150px;
  background: color-mix(in srgb, currentcolor 20%, transparent);
  border-radius: 100px;
  transform: translate(-50%, -50%);
}

.scale {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
  color: var(--family-blue);
  border-radius: 24px;
}

.ball {
  position: absolute;
  z-index: 2;
  width: 24px;
  height: 24px;
  background: currentColor;
  border-radius: 50%;
}
`,
  },
};
