// Auto-generated by scripts/generate-playgrounds.ts

export const BasicPresencePlayground = {
  files: {
    "/index.tsx": `import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";
import styles from "./styles.module.css";

export default function App() {
  const [show, setShow] = useState(true);

  return (
    <div className={styles.container}>
      <AnimatePresence mode="wait">
        {show && (
          <motion.div
            key="box"
            className={styles.box}
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            exit={{ opacity: 0, scale: 0.8 }}
            transition={{
              type: "spring",
              stiffness: 500,
              damping: 30,
            }}
          />
        )}
      </AnimatePresence>
      <button type="button" className={styles.button} onClick={() => setShow(!show)}>
        {show ? "Hide" : "Show"}
      </button>
    </div>
  );
}
`,
    "/styles.module.css": `.container {
  display: flex;
  flex-direction: column;
  gap: 24px;
  align-items: center;
  justify-content: center;
  min-height: 300px;
  padding: 24px;
}

.box {
  width: 100px;
  height: 100px;
  background: #171717;
  border-radius: 16px;
}

.button {
  padding: 8px 16px;
  font-size: 14px;
  font-weight: 500;
  color: #171717;
  cursor: pointer;
  background: #f5f5f5;
  border: 1px solid #e5e5e5;
  border-radius: 8px;
  transition: background 200ms ease;
}

.button:hover {
  background: #e5e5e5;
}
`,
  },
};
