// Auto-generated by scripts/generators/playgrounds

export const NestedExitsPlayground = {
  files: {
    "/App.tsx": `import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";
import styles from "./styles.module.css";

function ChildItem({ label }: { label: string }) {
  return (
    <motion.div
      className={styles.child}
      initial={{ opacity: 0, filter: "blur(10px)" }}
      animate={{ opacity: 1, filter: "blur(0px)" }}
      exit={{ opacity: 0, filter: "blur(10px)" }}
      transition={{
        duration: 0.5,
      }}
    >
      {label}
    </motion.div>
  );
}

interface ParentCardProps {
  showParent: boolean;
  propagate: boolean;
}

function ParentCard({ showParent, propagate }: ParentCardProps) {
  return (
    <div className={styles.column}>
      <div className={styles["column-content"]}>
        <AnimatePresence>
          {showParent && (
            <motion.div
              key="parent"
              className={styles.parent}
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              transition={{ duration: 1, ease: [0.19, 1, 0.22, 1] }}
            >
              <span className={styles.label}>
                {propagate ? "With Propagate" : "No Propagate"}
              </span>
              <div className={styles.children}>
                <AnimatePresence propagate={propagate}>
                  <ChildItem key="a" label="A" />
                  <ChildItem key="b" label="B" />
                  <ChildItem key="c" label="C" />
                </AnimatePresence>
              </div>
            </motion.div>
          )}
        </AnimatePresence>
      </div>
    </div>
  );
}

export default function App() {
  const [showParent, setShowParent] = useState(true);

  return (
    <div className={styles.root}>
      <div className={styles.container}>
        <ParentCard showParent={showParent} propagate={false} />
        <ParentCard showParent={showParent} propagate={true} />
      </div>
      <div className={styles.controls}>
        <button
          type="button"
          className={styles.button}
          onClick={() => setShowParent(!showParent)}
        >
          Toggle
        </button>
      </div>
    </div>
  );
}
`,
    "/styles.module.css": `.root {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  height: 100%;
}

.container {
  display: flex;
  flex: 1;
  gap: 48px;
  align-items: center;
  justify-content: center;
  width: 100%;
}

.column {
  display: flex;
  flex-direction: column;
  gap: 12px;
}

.column-content {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 120px;
}

.parent {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px;
  background: var(--gray-1);
  border-radius: 12px;
  box-shadow: var(--shadow-2);
}

.label {
  font-size: 12px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-10);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.children {
  display: flex;
  gap: 8px;
}

.child {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 48px;
  height: 48px;
  font-size: 14px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-12);
  background: var(--gray-2);
  border-radius: 8px;
  box-shadow: var(--shadow-2);
}

.controls {
  display: flex;
  gap: 8px;
  align-items: center;
  justify-content: center;
  width: 100%;
  padding: 16px 0;
  background: var(--gray-2);
  border-top: 1px solid var(--gray-4);
}

.button {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 32px;
  padding: 6px 12px;
  font-size: 14px;
  font-weight: 500;
  color: var(--gray-10);
  cursor: pointer;
  background: var(--gray-1);
  border: none;
  border-radius: 6px;
  box-shadow: var(--shadow-2);
}

.button:hover {
  color: var(--gray-12);
  background: var(--gray-3);
}

.button:active {
  transform: scale(0.98);
}
`,
  },
};
