// Auto-generated by scripts/generators/playgrounds

export const ManualExitPlayground = {
  files: {
    "/App.tsx": `import { AnimatePresence, motion, usePresence } from "motion/react";
import { useEffect, useState } from "react";
import styles from "./styles.module.css";

function Notification() {
  const [isPresent, safeToRemove] = usePresence();

  useEffect(() => {
    if (!isPresent) {
      const timer = setTimeout(() => {
        safeToRemove();
      }, 500);

      return () => clearTimeout(timer);
    }
  }, [isPresent, safeToRemove]);

  return (
    <motion.div
      className={styles.notification}
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.95 }}
      transition={{ type: "spring", stiffness: 500, damping: 30 }}
    >
      <span className={styles.title}>
        {isPresent ? "Notification" : "Cleaning up..."}
      </span>
      <span className={styles.message}>
        {isPresent ? "Click dismiss to trigger cleanup" : "Saving state..."}
      </span>
    </motion.div>
  );
}

export default function App() {
  const [isVisible, setIsVisible] = useState(true);

  return (
    <div className={styles.root}>
      <div className={styles.container}>
        <AnimatePresence>
          {isVisible && <Notification key="notification" />}
        </AnimatePresence>
      </div>
      <div className={styles.controls}>
        <button
          type="button"
          className={styles.button}
          onClick={() => setIsVisible(!isVisible)}
        >
          {isVisible ? "Dismiss" : "Show"}
        </button>
      </div>
    </div>
  );
}
`,
    "/styles.module.css": `.root {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
}

.container {
  display: flex;
  flex: 1;
  align-items: center;
  justify-content: center;
}

.notification {
  display: flex;
  flex-direction: column;
  gap: 4px;
  width: 256px;
  padding: 16px;
  background: var(--gray-1);
  border-radius: 8px;
  box-shadow: var(--shadow-2);
}

.title {
  font-size: 14px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-12);
}

.message {
  font-size: 13px;
  color: var(--gray-11);
}

.controls {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 16px 0;
  background: var(--gray-2);
  border-top: 1px solid var(--gray-4);
}

.button {
  height: 32px;
  padding: 6px 12px;
  font-size: 14px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-12);
  cursor: pointer;
  background: var(--gray-1);
  border: none;
  border-radius: 6px;
  box-shadow: var(--shadow-2);
}

.button:hover {
  background: var(--gray-3);
}

.button:active {
  transform: scale(0.98);
}
`,
  },
};
