// Auto-generated by scripts/generators/playgrounds

export const ManualExitPlayground = {
  files: {
    "/App.tsx": `import { AnimatePresence, motion, usePresence } from "motion/react";
import { useEffect, useState } from "react";
import { Button } from "@/components/button";
import { Controls } from "@/components/controls";
import styles from "./styles.module.css";

function Notification() {
  const [isPresent, safeToRemove] = usePresence();
  const [progress, setProgress] = useState(100);

  useEffect(() => {
    if (!isPresent) {
      // Simulate async cleanup (e.g., sending analytics, saving state)
      const cleanup = async () => {
        // Animate progress to 0
        const duration = 500;
        const steps = 20;
        const decrement = 100 / steps;
        const interval = duration / steps;

        for (let i = 0; i < steps; i++) {
          await new Promise((resolve) => setTimeout(resolve, interval));
          setProgress((prev) => Math.max(0, prev - decrement));
        }

        // Signal we're done
        safeToRemove();
      };

      cleanup();
    }
  }, [isPresent, safeToRemove]);

  return (
    <motion.div
      className={styles.notification}
      initial={{ opacity: 0, y: 20, scale: 0.95 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      exit={{ opacity: 0, y: -20, scale: 0.95 }}
      transition={{
        type: "spring",
        stiffness: 500,
        damping: 30,
      }}
    >
      <div className={styles.content}>
        <span className={styles.title}>
          {isPresent ? "Notification" : "Cleaning up..."}
        </span>
        <span className={styles.message}>
          {isPresent
            ? "Click dismiss to trigger async cleanup"
            : "Saving state before unmount"}
        </span>
      </div>
      <div className={styles.progressTrack}>
        <motion.div
          className={styles.progressBar}
          initial={{ width: "100%" }}
          animate={{ width: \`\${progress}%\` }}
          transition={{ duration: 0.05 }}
        />
      </div>
    </motion.div>
  );
}

export default function App() {
  const [isVisible, setIsVisible] = useState(true);

  return (
    <div className={styles.root}>
      <div className={styles.container}>
        <AnimatePresence>
          {isVisible && <Notification key="notification" />}
        </AnimatePresence>
      </div>
      <Controls>
        <Button onClick={() => setIsVisible(!isVisible)}>
          {isVisible ? "Dismiss" : "Show"}
        </Button>
      </Controls>
    </div>
  );
}
`,
    "/styles.module.css": `.root {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
  align-items: center;
  width: 100%;
}

.container {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 200px;
}

.notification {
  display: flex;
  flex-direction: column;
  gap: 12px;
  width: 280px;
  padding: 16px;
  background: var(--gray-3);
  border: 1px solid var(--gray-6);
  border-radius: 12px;
}

.content {
  display: flex;
  flex-direction: column;
  gap: 4px;
}

.title {
  font-size: 14px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-12);
}

.message {
  font-size: 13px;
  color: var(--gray-11);
}

.progress-track {
  height: 4px;
  overflow: hidden;
  background: var(--gray-5);
  border-radius: 2px;
}

.progress-bar {
  height: 100%;
  background: var(--gray-9);
  border-radius: 2px;
}
`,
  },
};
