// Auto-generated by scripts/generate-playgrounds.ts

export const PresenceStatePlayground = {
  files: {
    "/App.tsx": `import { AnimatePresence, motion, useIsPresent } from "motion/react";
import { useState } from "react";
import { Button } from "@/components/button";
import { Controls } from "@/components/controls";
import styles from "./styles.module.css";

function Card() {
  const isPresent = useIsPresent();

  return (
    <motion.div
      className={styles.card}
      initial={{ opacity: 0, scale: 0.9 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.9 }}
      transition={{
        type: "spring",
        stiffness: 500,
        damping: 30,
      }}
    >
      <span className={styles.status} data-present={isPresent}>
        {isPresent ? "Present" : "Exiting..."}
      </span>
    </motion.div>
  );
}

export default function App() {
  const [isVisible, setIsVisible] = useState(true);

  return (
    <div className={styles.root}>
      <div className={styles.container}>
        <AnimatePresence>{isVisible && <Card key="card" />}</AnimatePresence>
      </div>
      <Controls>
        <Button onClick={() => setIsVisible(!isVisible)}>
          {isVisible ? "Remove" : "Add"}
        </Button>
      </Controls>
    </div>
  );
}
`,
    "/styles.module.css": `.root {
  display: flex;
  flex-direction: column;
  gap: 1.5rem;
  align-items: center;
  width: 100%;
}

.container {
  position: relative;
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 200px;
}

.card {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 160px;
  height: 100px;
  background: var(--gray-3);
  border: 1px solid var(--gray-6);
  border-radius: 12px;
}

.status {
  font-size: 0.875rem;
  font-weight: 500;
}

.status[data-present="true"] {
  color: var(--gray-12);
}

.status[data-present="false"] {
  color: var(--gray-9);
}
`,
  },
};
