// Auto-generated by scripts/generate-playgrounds.ts

export const SolidDrawingPlayground = {
  files: {
    "/App.tsx": `import { motion } from "motion/react";
import { useState } from "react";
import { Button } from "@/components/button";
import { Controls } from "@/components/controls";
import styles from "./styles.module.css";

const EASING = {
  inOutCubic: [0.645, 0.045, 0.355, 1] as const,
  outExpo: [0.19, 1, 0.22, 1] as const,
};

const ORBIT_DURATION = 2.5;
const RING_DURATION = 2;

export default function App() {
  const [isPlaying, setIsPlaying] = useState(true);

  const paused = !isPlaying;

  function toggle() {
    setIsPlaying((prev) => !prev);
  }

  return (
    <div className={styles["solid-drawing"]}>
      <div className={styles["globe-container"]}>
        <div className={styles["globe-scene"]}>
          <motion.svg viewBox="0 0 128 128" className={styles["globe-svg"]}>
            <title>Globe</title>
            <circle cx="64" cy="64" r="36" fill="var(--surface)" />
            <motion.circle
              cx="64"
              cy="64"
              r="26"
              fill="var(--surface)"
              stroke="var(--accent-muted)"
              strokeWidth="6"
              initial={{
                strokeDasharray: "2 4.09",
              }}
              animate={{
                rotate: isPlaying ? [0, 360] : 0,
                strokeDasharray: paused ? "2 0" : "2 4.09",
              }}
              transition={{
                rotate: {
                  repeat: isPlaying ? Number.POSITIVE_INFINITY : 0,
                  ease: "linear",
                  duration: RING_DURATION,
                },
                strokeDasharray: {
                  duration: 0.7,
                  ease: EASING.inOutCubic,
                },
              }}
            />
            <motion.circle
              cx="64"
              cy="64"
              r="16"
              fill={paused ? "var(--complete)" : "var(--surface)"}
              initial={{ scale: 0 }}
              animate={{ scale: paused ? 1 : 0 }}
              transition={{
                duration: 0.4,
                ease: EASING.inOutCubic,
              }}
            />
          </motion.svg>

          <motion.div
            className={styles["orbit-marker"]}
            data-paused={paused}
            initial={{
              transform:
                "translate(-50%, -50%) rotateY(20deg) translateZ(48px) rotateY(340deg)",
            }}
            animate={
              paused
                ? {
                    transform:
                      "translate(-50%, -50%) rotateY(20deg) translateZ(48px) rotateY(340deg)",
                  }
                : {
                    transform: [
                      "translate(-50%, -50%) rotateY(360deg) translateZ(48px) rotateY(0deg)",
                      "translate(-50%, -50%) rotateY(0deg) translateZ(48px) rotateY(360deg)",
                    ],
                  }
            }
            transition={
              paused
                ? {
                    ease: EASING.outExpo,
                    duration: 3,
                  }
                : {
                    repeat: Number.POSITIVE_INFINITY,
                    ease: "linear",
                    duration: ORBIT_DURATION,
                  }
            }
          >
            <div className={styles["orbit-layer-back"]} />
            <div className={styles["orbit-layer-middle"]} />
            <motion.div
              className={styles["orbit-layer-front"]}
              animate={{
                width: paused ? 0 : 8,
                height: paused ? 0 : 8,
              }}
              transition={{
                duration: 0.4,
                ease: EASING.inOutCubic,
              }}
            />
          </motion.div>
        </div>
      </div>
      <Controls className={styles.controls}>
        <Button onClick={() => toggle()}>{isPlaying ? "Pause" : "Play"}</Button>
      </Controls>
    </div>
  );
}
`,
    "/styles.module.css": `.solid-drawing {
  --accent: var(--pink-9);
  --accent-muted: color-mix(in srgb, var(--pink-9) 20%, transparent);
  --complete: var(--sky-9);
  --surface: var(--gray-1);
  position: relative;
  display: flex;
  flex: 1 0 0;
  flex-direction: column;

  width: 100%;
  height: 384px;
}

.globe-container {
  display: flex;
  align-items: center;
  justify-content: center;
  height: 100%;
}

.globe-scene {
  rotate: -45deg;
  transform-style: preserve-3d;
  perspective: 100px;
  position: relative;
}

.globe-svg {
  width: 128px;
  height: 128px;
}

.orbit-marker {
  position: absolute;
  top: 50%;
  left: 50%;
  width: 24px;
  height: 24px;
  background: var(--surface);
  border-radius: 50%;
  transform: translate(-50%, -50%);
}

.orbit-layer-back,
.orbit-layer-middle,
.orbit-layer-front {
  position: absolute;
  top: 50%;
  left: 50%;
  border-radius: 50%;
  transform: translate(-50%, -50%);
  transition: background 0.4s cubic-bezier(0.645, 0.045, 0.355, 1);
}

.orbit-layer-back {
  z-index: 1;
  width: 24px;
  height: 24px;
  background: var(--surface);
}

.orbit-layer-middle {
  z-index: 2;
  width: 16px;
  height: 16px;
  background: var(--accent);
}

.orbit-layer-front {
  z-index: 3;
  width: 8px;
  height: 8px;
  background: var(--surface);
}

.orbit-marker[data-paused="true"] .orbit-layer-middle {
  background: var(--complete);
}

.toggle-button {
  position: absolute;
  bottom: 24px;
  left: 50%;
  z-index: 1;
  display: flex;
  align-items: center;
  justify-content: center;
  height: 32px;
  padding: 12px;
  font-size: 14px;
  color: var(--gray-11);
  cursor: pointer;
  user-select: none;
  transform: translateX(-50%);
  transform-origin: center center;
  transition: all 0.2s ease;
}

.toggle-button::before {
  position: absolute;
  top: 0;
  left: 0;
  z-index: -1;
  width: 100%;
  height: 100%;
  content: "";
  background: var(--gray-2);
  border-radius: 8px;
  opacity: 0;
  scale: 0.98;
  transition: all 0.2s ease;
}

.toggle-button:hover {
  color: var(--gray-12);
}

.toggle-button:hover::before {
  opacity: 1;
  scale: 1;
}

.toggle-button:active {
  scale: 0.99;
}
`,
  },
};
