// Auto-generated by scripts/generators/playgrounds

export const ExaggerationPlayground = {
  files: {
    "/App.tsx": `import styles from "./styles.module.css";

export default function App() {
  return (
    <div className={styles.container}>
      <video
        autoPlay
        muted
        loop
        playsInline
        src="/content/12-principles-of-animation/videos/exaggeration.mp4"
        style={{
          width: "100%",
          height: 540,
          objectFit: "cover",
        }}
      />
    </div>
  );
}
`,
    "/styles.module.css": `.container {
  position: relative;
  display: flex;
  flex-direction: column;
  gap: 12px;
  align-items: center;
  justify-content: center;
  height: 384px;

  &::before {
    position: absolute;
    inset: 0;
    z-index: 10;
    content: "";
    background: linear-gradient(
      to bottom,
      black 20%,
      transparent 50%,
      black 90%
    );
  }
}
`,
  },
};
