import fs from "node:fs";
import path from "node:path";

const CONTENT_DIR = path.join(process.cwd(), "content");

interface PlaygroundConfig {
  files: Record<string, string>;
  dependencies?: Record<string, string>;
}

/**
 * Scans for demo folders containing playgrounds/app.tsx and playgrounds/app.module.css,
 * then generates playground files.
 *
 * Expected structure:
 *   demos/
 *     01-demo-name/
 *       index.tsx           (the real demo component)
 *       styles.module.css   (the real styles)
 *       playgrounds/
 *         app.tsx           (playground code with CSS Modules)
 *         app.module.css    (playground styles)
 *         index.ts          (auto-generated)
 */
function findDemoFolders(dir: string): string[] {
  const demos: string[] = [];

  function walk(currentDir: string) {
    const entries = fs.readdirSync(currentDir, { withFileTypes: true });

    for (const entry of entries) {
      const fullPath = path.join(currentDir, entry.name);

      if (entry.isDirectory()) {
        // Check if this is a demos folder
        if (entry.name === "demos") {
          // Look for numbered demo folders inside
          const demoEntries = fs.readdirSync(fullPath, { withFileTypes: true });
          for (const demoEntry of demoEntries) {
            if (demoEntry.isDirectory()) {
              const demoPath = path.join(fullPath, demoEntry.name);
              const playgroundsPath = path.join(demoPath, "playgrounds");
              const appPath = path.join(playgroundsPath, "app.tsx");
              const stylesPath = path.join(playgroundsPath, "app.module.css");

              if (fs.existsSync(appPath) && fs.existsSync(stylesPath)) {
                demos.push(demoPath);
              }
            }
          }
        } else {
          walk(fullPath);
        }
      }
    }
  }

  walk(dir);
  return demos;
}

function extractDependencies(code: string): Record<string, string> {
  const deps: Record<string, string> = {};

  // Match import statements
  const importRegex = /import\s+.*?\s+from\s+["']([^"']+)["']/g;
  let match: RegExpExecArray | null = importRegex.exec(code);

  while (match !== null) {
    const pkg = match[1];
    // Skip relative imports and css imports
    if (pkg.startsWith(".") || pkg.endsWith(".css")) {
      match = importRegex.exec(code);
      continue;
    }

    // Get the package name (handle scoped packages)
    const pkgName = pkg.startsWith("@")
      ? pkg.split("/").slice(0, 2).join("/")
      : pkg.split("/")[0];

    // Add with "latest" version
    deps[pkgName] = "latest";
    match = importRegex.exec(code);
  }

  return deps;
}

function escapeTemplateString(str: string): string {
  return str.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$/g, "\\$");
}

/**
 * Converts a folder name like "01-basic-presence" to "BasicPresencePlayground"
 */
function toPascalCase(folderName: string): string {
  // Remove leading number prefix (e.g., "01-")
  const withoutPrefix = folderName.replace(/^\d+-/, "");
  // Convert kebab-case to PascalCase and add "Playground" suffix
  return `${withoutPrefix
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join("")}Playground`;
}

function generatePlayground(demoPath: string): void {
  const playgroundsDir = path.join(demoPath, "playgrounds");
  const appPath = path.join(playgroundsDir, "app.tsx");
  const stylesPath = path.join(playgroundsDir, "app.module.css");
  const outputPath = path.join(playgroundsDir, "index.ts");

  const demoName = path.basename(demoPath);
  const exportName = toPascalCase(demoName);

  const appCode = fs.readFileSync(appPath, "utf-8");
  const stylesCode = fs.readFileSync(stylesPath, "utf-8");

  const dependencies = extractDependencies(appCode);

  const _config: PlaygroundConfig = {
    files: {
      "/index.tsx": appCode,
      "/styles.module.css": stylesCode,
    },
    dependencies,
  };

  const output = `// Auto-generated by scripts/generate-playgrounds.ts

export const ${exportName} = {
  files: {
    "/index.tsx": \`${escapeTemplateString(appCode)}\`,
    "/styles.module.css": \`${escapeTemplateString(stylesCode)}\`,
  },
};
`;

  fs.writeFileSync(outputPath, output);
  console.log(`Generated: ${path.relative(process.cwd(), outputPath)}`);
}

function main() {
  console.log("Scanning for playground demos...\n");

  const demos = findDemoFolders(CONTENT_DIR);

  if (demos.length === 0) {
    console.log("No demos found with app.tsx and app.module.css files.");
    console.log("\nExpected structure:");
    console.log("  content/*/demos/*/app.tsx");
    console.log("  content/*/demos/*/app.module.css");
    return;
  }

  console.log(`Found ${demos.length} demo(s):\n`);

  for (const demoPath of demos) {
    generatePlayground(demoPath);
  }

  console.log("\nDone!");
}

main();
