// Auto-generated by scripts/generators/playgrounds

export const NestedExitsPlayground = {
  files: {
    "/App.tsx": `import { AnimatePresence, motion } from "motion/react";
import { useState } from "react";
import styles from "./styles.module.css";

const items = ["A", "B", "C"];

export default function App() {
  const [show, setShow] = useState(true);

  const renderCard = (propagate: boolean) => (
    <AnimatePresence>
      {show && (
        <motion.div
          key="card"
          className={styles.card}
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          exit={{ opacity: 0, scale: 0.95 }}
          transition={{ duration: 0.8, ease: [0.19, 1, 0.22, 1] }}
        >
          <span className={styles.label}>
            {propagate ? "With Propagate" : "No Propagate"}
          </span>
          <div className={styles.items}>
            <AnimatePresence propagate={propagate}>
              {items.map((item) => (
                <motion.div
                  key={item}
                  className={styles.item}
                  initial={{ opacity: 0, filter: "blur(10px)" }}
                  animate={{ opacity: 1, filter: "blur(0px)" }}
                  exit={{ opacity: 0, filter: "blur(10px)" }}
                  transition={{ duration: 0.5 }}
                >
                  {item}
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );

  return (
    <div className={styles.root}>
      <div className={styles.cards}>
        {renderCard(false)}
        {renderCard(true)}
      </div>
      <div className={styles.controls}>
        <button
          type="button"
          className={styles.button}
          onClick={() => setShow(!show)}
        >
          Toggle
        </button>
      </div>
    </div>
  );
}
`,
    "/styles.module.css": `.root {
  display: flex;
  flex-direction: column;
  width: 100%;
  height: 100%;
}

.cards {
  display: flex;
  flex: 1;
  align-items: center;
  justify-content: space-around;

  @media (max-width: 640px) {
    flex-direction: column;
    gap: 24px;
    justify-content: center;
  }
}

.card {
  display: flex;
  flex-direction: column;
  gap: 12px;
  padding: 16px;
  background: var(--gray-1);
  border-radius: 12px;
  box-shadow: var(--shadow-2);
}

.label {
  font-size: 12px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-10);
  text-transform: uppercase;
  letter-spacing: 0.05em;
}

.items {
  display: flex;
  gap: 8px;
}

.item {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 48px;
  height: 48px;
  font-size: 14px;
  font-weight: var(--font-weight-medium);
  color: var(--gray-12);
  background: var(--gray-2);
  border-radius: 8px;
  box-shadow: var(--shadow-2);
}

.controls {
  display: flex;
  align-items: center;
  justify-content: center;
  padding: 16px 0;
  background: var(--gray-2);
  border-top: 1px solid var(--gray-4);
}

.button {
  height: 32px;
  padding: 6px 12px;
  font-size: 14px;
  font-weight: 500;
  color: var(--gray-10);
  cursor: pointer;
  background: var(--gray-1);
  border: none;
  border-radius: 6px;
  box-shadow: var(--shadow-2);
}

.button:hover {
  color: var(--gray-12);
  background: var(--gray-3);
}

.button:active {
  transform: scale(0.98);
}
`,
  },
};
